router:
  build: .
  environment:
   - DOCKER_CERT_PATH=/ssl
   - DOCKER_HOST
   - DOCKER_TLS_VERIFY
   - DOCKER_MACHINE_NAME
  ports:
   - "5000:5000"
  volumes:
   - .:/code
   - /Users/canon/.docker/machine/machines/dev:/ssl

www:
  build: proxy/
  links:
   - router
  ports:
   - "8080:80"
   - "8443:443"
  volumes:
   - ssl:/etc/nginx/ssl/
